version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ONExALar
    ports:
      - "5050:80"
    networks:
      - app-net

networks:
  app-net:
    external: true